### ISSUE TITLE
Support for Redis Cluster?

### ISSUE THREAD

**Issue by thallium205** [graknlabs/redis-mock#15]
When trying to instantiate a JedisCluster:
```
try {
    RedisServer redisServer;
    redisServer = RedisServer.newRedisServer();
    redisServer.start();
    return new JedisCluster(new HostAndPort(redisServer.getHost(), redisServer.getBindPort()));
} catch (IOException ex) {
    System.out.println("WARNING: Mock Redis server is unavailable.");
    return null;
}
```
The following error results:
```
java.lang.UnsupportedOperationException: Unsupported operation 'cluster'
	at ai.grakn.redismock.commands.RedisOperationExecutor.buildSimpleOperation(RedisOperationExecutor.java:135)
	at ai.grakn.redismock.commands.RedisOperationExecutor.execCommand(RedisOperationExecutor.java:154)
	at ai.grakn.redismock.RedisClient.run(RedisClient.java:48)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by maksymkovalenko** [comment]
In my project, i'm using Redis in cluster mode only. Unfortunately, it looks like I'm not able to use `redis-mock` currently
