### ISSUE TITLE
Support for Hash commands (RedisHashCommands)

### ISSUE THREAD

**Issue by 66303** [graknlabs/redis-mock#16]
Is there a plan to add support for RedisHashCommands?

`java.lang.UnsupportedOperationException: Unsupported operation 'hset'
at ai.grakn.redismock.commands.RedisOperationExecutor.buildSimpleOperation(RedisOperationExecutor.java:135)
at ai.grakn.redismock.commands.RedisOperationExecutor.execCommand(RedisOperationExecutor.java:154)
at ai.grakn.redismock.RedisClient.run(RedisClient.java:48)
at java.lang.Thread.run(Thread.java:745)`

**Comment by fppt** [comment]
No plans for the moment @66303, but it should be simple to add. I will try to get around to it at some point.

**Comment by 66303** [comment]
@fppt thanks

**Comment by OfekCyberX** [comment]
hash operations would be great :) Also waiting for this feature.
BTW the mock is working great! Thank you

**Comment by djotanov** [comment]
Yeah, a lot of us are using hash operations. It would be great to have that

**Comment by petehannam** [comment]
I've added a PR for this.

**Comment by rivancic** [comment]
Looking forward for set and ordered set operations :smile:
