### ISSUE TITLE
Support for info command

### ISSUE THREAD

**Issue by dpfundt** [graknlabs/redis-mock#18]
Firstly, thanks for sharing this good plugin. I'm trying to use it with Spring Boot. It appears that the actuator health checks make use of the INFO command in Redis, which doesn't appear to be supported currently?

Here's the stack trace, although it's probably not that useful to you guys..

```2018-04-10 15:44:35.918  WARN 13236 --- [2)-172.23.56.49] o.s.b.a.h.RedisHealthIndicator           : Health check failed

org.springframework.dao.InvalidDataAccessApiUsageException: Unsupported operation 'info'; nested exception is redis.clients.jedis.exceptions.JedisDataException: Unsupported operation 'info'
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:64) ~[spring-data-redis-1.8.10.RELEASE.jar:?]
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:41) ~[spring-data-redis-1.8.10.RELEASE.jar:?]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37) ~[spring-data-redis-1.8.10.RELEASE.jar:?]
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:37) ~[spring-data-redis-1.8.10.RELEASE.jar:?]
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:241) ~[spring-data-redis-1.8.10.RELEASE.jar:?]
	at org.springframework.data.redis.connection.jedis.JedisConnection.info(JedisConnection.java:616) ~[spring-data-redis-1.8.10.RELEASE.jar:?]
	at org.springframework.boot.actuate.health.RedisHealthIndicator.doHealthCheck(RedisHealthIndicator.java:62) ~[spring-boot-actuator-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:43) ~[spring-boot-actuator-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:68) ~[spring-boot-actuator-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.actuate.endpoint.HealthEndpoint.invoke(HealthEndpoint.java:85) ~[spring-boot-actuator-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.actuate.endpoint.HealthEndpoint.invoke(HealthEndpoint.java:35) ~[spring-boot-actuator-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.actuate.endpoint.jmx.DataEndpointMBean.getData(DataEndpointMBean.java:46) ~[spring-boot-actuator-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71) ~[?:1.8.0_92]
	at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275) ~[?:1.8.0_92]
	at javax.management.modelmbean.RequiredModelMBean$4.run(RequiredModelMBean.java:1252) ~[?:1.8.0_92]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_92]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76) ~[?:1.8.0_92]
	at javax.management.modelmbean.RequiredModelMBean.invokeMethod(RequiredModelMBean.java:1246) ~[?:1.8.0_92]
	at javax.management.modelmbean.RequiredModelMBean.invoke(RequiredModelMBean.java:1085) ~[?:1.8.0_92]
	at org.springframework.jmx.export.SpringModelMBean.invoke(SpringModelMBean.java:90) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at javax.management.modelmbean.RequiredModelMBean.getAttribute(RequiredModelMBean.java:1562) ~[?:1.8.0_92]
	at org.springframework.jmx.export.SpringModelMBean.getAttribute(SpringModelMBean.java:109) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647) ~[?:1.8.0_92]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678) ~[?:1.8.0_92]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445) ~[?:1.8.0_92]
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76) ~[?:1.8.0_92]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309) ~[?:1.8.0_92]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401) ~[?:1.8.0_92]
	at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639) ~[?:1.8.0_92]
	at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324) ~[?:1.8.0_92]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) ~[?:1.8.0_92]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) ~[?:1.8.0_92]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_92]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) ~[?:1.8.0_92]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568) ~[?:1.8.0_92]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826) ~[?:1.8.0_92]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683) ~[?:1.8.0_92]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_92]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: redis.clients.jedis.exceptions.JedisDataException: Unsupported operation 'info'
	at redis.clients.jedis.Protocol.processError(Protocol.java:127) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.Protocol.process(Protocol.java:161) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.Protocol.read(Protocol.java:215) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:259) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:248) ~[jedis-2.9.0.jar:?]
	at redis.clients.jedis.BinaryJedis.info(BinaryJedis.java:2807) ~[jedis-2.9.0.jar:?]
	at org.springframework.data.redis.connection.jedis.JedisConnection.info(JedisConnection.java:614) ~[spring-data-redis-1.8.10.RELEASE.jar:?]
	... 46 more
```

Cheers.

**Comment by randysecrist** [comment]
+1 for this;  if you would consider accepting a PR ; I may take this on and push it up.  Let me know.
