### ISSUE TITLE
Support for eval operations

### ISSUE THREAD

**Issue by HurmuzacheCiprian** [graknlabs/redis-mock#24]
Hi,

I saw that there is no support for eval operations and I think it would be important to have it because there are lots of applications which rely on Lua scripts. I know that this is a simple in-memory Redis mock, but if there is no use case for adding support for eval operations then I think it would be great if you could specify in the Readme.md file that eval operations are not supported at the moment. Cheers

`ERROR ai.grakn.redismock.commands.RedisOperationExecutor - Malformed request
java.lang.UnsupportedOperationException: Unsupported operation 'eval'
	at ai.grakn.redismock.commands.RedisOperationExecutor.buildSimpleOperation(RedisOperationExecutor.java:135)
	at ai.grakn.redismock.commands.RedisOperationExecutor.execCommand(RedisOperationExecutor.java:154)
	at ai.grakn.redismock.RedisClient.run(RedisClient.java:48)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by picarsite** [comment]
Did you find a different solution for testing your lua scripts?
